### PR TITLE
Logo draft

### PR DESCRIPTION
**Pull request by uetchy**
@azu Just logo sketches. I can't make up my mind which combination is better for textlint so please feel free to post feedback about combination of symbols, typefaces and colours.

### CODE REVIEW

**Comment by azu** [comment]
fmm, it is difficutlt to select one.
Symbol C looks nice(T + L represent textlint).
- Symbol: C > B > A
- Typface: C > A > B
- Color: B > A > C and I like [the color](https://github.com/textlint/textlint/issues/56#issuecomment-160050653) too.

f89640fa-9518-11e5-9bee-fcacf9446667 png png 2512x1523 px - 63 2015-12-28 20-27-18

I hope you find it informative.

**Comment by uetchy** [comment]
Thank you for your review!
I made second draft based on your opinion.
How about this?

**Comment by azu** [comment]
@uetchy Thanks.
If the logo size is tiny, Symbol **E** is hard to understand what to represent.
Symbol **D** with color gradient is also hard to make out this for the same reason.
(Symbol represent "T")
iteration2 png png 8470x1523 px - 14 2016-01-26 10-22-54

**Comment by azu** [comment]
So, I feeling the best is Symbol C. p b
How about this?

**Comment by uetchy** [comment]
Indeed. I added final proposal into /logo.

**Comment by azu** [comment]
Great! :+1:

**Comment by azu** [comment]
@uetchy I will merge it and make it under CC0.
Are you OK?

**Comment by uetchy** [comment]
Yeah almost. Should we leave **logo-iteration** folder, or squash them all?

**Comment by uetchy** [comment]
Also we need a trademark usage policy.

**Comment by azu** [comment]
> Should we leave logo-iteration folder, or squash them all?

Yes. it should be removed.

> Also we need a trademark usage policy.

We'll add following text to README.md. ( very inspired by [power-assert](https://github.com/power-assert-js/power-assert-js-logo) ) 

---

Created by [Yasuaki Uechi (@uetchy)](https://github.com/uetchy)

<p xmlns:dct="http://purl.org/dc/terms/">
  <a rel="license"
     href="http://creativecommons.org/publicdomain/zero/1.0/">
    CC0
  </a>
  <br />
  To the extent possible under law,
  <a rel="dct:publisher"
     href="https://github.com/armorik83">
    <span property="dct:title">Yasuaki Uechi </span></a>
  has waived all copyright and related or neighboring rights to
  <span property="dct:title">textlint logo</span>.
</p>

---

**Comment by uetchy** [comment]
I squashed commits and added the policy to README.

**Comment by azu** [comment]
Merge! :tada:

**Comment by azu** [comment]
@uetchy Thanks again for nice work!

**Comment by uetchy** [comment]
Hooray! :raised_hands:

**Pull request merged**
